os:
  - Visual Studio 2017
  - Visual Studio 2019

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake --version

build_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build . --config "%CONFIG%"