dist: bionic

language: cpp

matrix:
    include:
      - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-9
              - cmake
        env:
          - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

      - os: linux
        addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-trusty-7.0
              packages:
                - clang-7.0
                - cmake
        env:
           - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

      - os: osx
        osx_image: xcode11.1

      - os: osx
        osx_image: xcode8
        env:
           - MATRIX_EVAL="brew install gcc9 && CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .